name: Changelog and Release
run-name: Create Changelog and Release by @${{ github.actor }}
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conventional Commit Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github_token: ${{ secrets.CHANGELOG_RELEASE }}

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_RELEASE }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
